# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-03 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failed_attempts', '0002_auto_20151224_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedattempt',
            name='IP',
            field=models.GenericIPAddressField(null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='failedattempt',
            name='failures',
            field=models.PositiveIntegerField(default=0, verbose_name='Failures'),
        ),
        migrations.AlterField(
            model_name='failedattempt',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Last failed attempt'),
        ),
        migrations.AlterField(
            model_name='failedattempt',
            name='username',
            field=models.CharField(max_length=255, verbose_name='Username'),
        ),
    ]
